name: unit test
on: 
  - "push"
  - "pull_request"
jobs:
  unit-test:
    # Ref: https://github.com/actions/runner-images/tree/main/images/linux
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run compile
    # Ref: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
    - run: xvfb-run -a npm run test
      if: runner.os == 'Linux'
    - run: npm run test
      if: runner.os != 'Linux'